# Generated by Django 5.2.17 on 2026-10-01 19:15

import apps.core.uploads
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation_status', models.CharField(choices=[('none', 'Not translated'), ('machine', 'Machine translated'), ('reviewed', 'Reviewed by a human')], db_index=True, default='none', help_text="Set to 'Machine translated' by the auto-translate action. A human sets it to 'Reviewed' after checking the wording.", max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', help_text='Only published rows are served to the public site.', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically the first time this is published.', null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True, validators=[django.core.validators.RegexValidator(message='Lower-case English words separated by single hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('client_name', models.CharField(blank=True, max_length=160)),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10), default=list, size=None)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('description_zh', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('features', models.TextField(blank=True, help_text='Plain text: one feature per line.')),
                ('features_en', models.TextField(blank=True, help_text='Plain text: one feature per line.', null=True)),
                ('features_es', models.TextField(blank=True, help_text='Plain text: one feature per line.', null=True)),
                ('features_fr', models.TextField(blank=True, help_text='Plain text: one feature per line.', null=True)),
                ('features_de', models.TextField(blank=True, help_text='Plain text: one feature per line.', null=True)),
                ('features_zh', models.TextField(blank=True, help_text='Plain text: one feature per line.', null=True)),
                ('features_ar', models.TextField(blank=True, help_text='Plain text: one feature per line.', null=True)),
                ('app_store_url', models.URLField(blank=True)),
                ('play_store_url', models.URLField(blank=True)),
                ('icon_image', models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('mobile/icons'), validators=[apps.core.uploads.validate_upload_size])),
                ('downloads', models.PositiveBigIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileAppScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation_status', models.CharField(choices=[('none', 'Not translated'), ('machine', 'Machine translated'), ('reviewed', 'Reviewed by a human')], db_index=True, default='none', help_text="Set to 'Machine translated' by the auto-translate action. A human sets it to 'Reviewed' after checking the wording.", max_length=16)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('image', models.ImageField(upload_to=apps.core.uploads.UploadTo('mobile/screenshots'), validators=[apps.core.uploads.validate_upload_size])),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('caption_en', models.CharField(blank=True, max_length=240, null=True)),
                ('caption_es', models.CharField(blank=True, max_length=240, null=True)),
                ('caption_fr', models.CharField(blank=True, max_length=240, null=True)),
                ('caption_de', models.CharField(blank=True, max_length=240, null=True)),
                ('caption_zh', models.CharField(blank=True, max_length=240, null=True)),
                ('caption_ar', models.CharField(blank=True, max_length=240, null=True)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
