# Generated by Django 5.2.17 on 2026-10-01 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobile_development', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevelopmentCaseStudy',
            fields=[
            ],
            options={
                'verbose_name': 'Case study',
                'verbose_name_plural': 'Case studies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portfolio.casestudy',),
        ),
        migrations.AddField(
            model_name='mobileappscreenshot',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='mobile_development.mobileapp'),
        ),
    ]
