# Generated by Django 5.2.17 on 2026-10-01 22:37

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_development', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileapp',
            name='icon_image',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('mobile/icons'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='mobileappscreenshot',
            name='image',
            field=models.ImageField(upload_to=apps.core.uploads.UploadTo('mobile/screenshots'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
    ]
