# Generated by Django 5.2.17 on 2026-10-01 23:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('object_id', models.CharField(max_length=64)),
                ('locale', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese (Simplified)'), ('ar', 'Arabic')], max_length=2)),
                ('fields', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('success', 'Translated'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, max_length=12)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('model_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Translation log',
                'verbose_name_plural': 'Translation log',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
