# Generated by Django 5.2.17 on 2026-10-01 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_automation', '0001_initial'),
        ('core', '0006_video'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAutomationCaseStudy',
            fields=[
            ],
            options={
                'verbose_name': 'Case study',
                'verbose_name_plural': 'Case studies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portfolio.casestudy',),
        ),
        migrations.AddField(
            model_name='automationusecase',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_use_cases', to='core.industry'),
        ),
    ]
