# Generated by Django 5.2.17 on 2026-10-01 22:37

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_automation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='logo',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('integrations'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
    ]
