# Generated by Django 5.2.17 on 2026-10-01 19:15

import apps.core.uploads
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_stat_options_alter_teammember_options'),
        ('services', '0003_service_published_at_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation_status', models.CharField(choices=[('none', 'Not translated'), ('machine', 'Machine translated'), ('reviewed', 'Reviewed by a human')], db_index=True, default='none', help_text="Set to 'Machine translated' by the auto-translate action. A human sets it to 'Reviewed' after checking the wording.", max_length=16)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120, null=True)),
                ('name_es', models.CharField(max_length=120, null=True)),
                ('name_fr', models.CharField(max_length=120, null=True)),
                ('name_de', models.CharField(max_length=120, null=True)),
                ('name_zh', models.CharField(max_length=120, null=True)),
                ('name_ar', models.CharField(max_length=120, null=True)),
                ('slug', models.SlugField(max_length=180, unique=True, validators=[django.core.validators.RegexValidator(message='Lower-case English words separated by single hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('description_zh', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation_status', models.CharField(choices=[('none', 'Not translated'), ('machine', 'Machine translated'), ('reviewed', 'Reviewed by a human')], db_index=True, default='none', help_text="Set to 'Machine translated' by the auto-translate action. A human sets it to 'Reviewed' after checking the wording.", max_length=16)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=80)),
                ('name_en', models.CharField(max_length=80, null=True)),
                ('name_es', models.CharField(max_length=80, null=True)),
                ('name_fr', models.CharField(max_length=80, null=True)),
                ('name_de', models.CharField(max_length=80, null=True)),
                ('name_zh', models.CharField(max_length=80, null=True)),
                ('name_ar', models.CharField(max_length=80, null=True)),
                ('slug', models.SlugField(max_length=180, unique=True, validators=[django.core.validators.RegexValidator(message='Lower-case English words separated by single hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation_status', models.CharField(choices=[('none', 'Not translated'), ('machine', 'Machine translated'), ('reviewed', 'Reviewed by a human')], db_index=True, default='none', help_text="Set to 'Machine translated' by the auto-translate action. A human sets it to 'Reviewed' after checking the wording.", max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', help_text='Only published rows are served to the public site.', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically the first time this is published.', null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Falls back to the page title. Around 60 characters reads best in results.', max_length=70)),
                ('meta_title_en', models.CharField(blank=True, help_text='Falls back to the page title. Around 60 characters reads best in results.', max_length=70, null=True)),
                ('meta_title_es', models.CharField(blank=True, help_text='Falls back to the page title. Around 60 characters reads best in results.', max_length=70, null=True)),
                ('meta_title_fr', models.CharField(blank=True, help_text='Falls back to the page title. Around 60 characters reads best in results.', max_length=70, null=True)),
                ('meta_title_de', models.CharField(blank=True, help_text='Falls back to the page title. Around 60 characters reads best in results.', max_length=70, null=True)),
                ('meta_title_zh', models.CharField(blank=True, help_text='Falls back to the page title. Around 60 characters reads best in results.', max_length=70, null=True)),
                ('meta_title_ar', models.CharField(blank=True, help_text='Falls back to the page title. Around 60 characters reads best in results.', max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Around 155 characters. Falls back to the intro.', max_length=170)),
                ('meta_description_en', models.CharField(blank=True, help_text='Around 155 characters. Falls back to the intro.', max_length=170, null=True)),
                ('meta_description_es', models.CharField(blank=True, help_text='Around 155 characters. Falls back to the intro.', max_length=170, null=True)),
                ('meta_description_fr', models.CharField(blank=True, help_text='Around 155 characters. Falls back to the intro.', max_length=170, null=True)),
                ('meta_description_de', models.CharField(blank=True, help_text='Around 155 characters. Falls back to the intro.', max_length=170, null=True)),
                ('meta_description_zh', models.CharField(blank=True, help_text='Around 155 characters. Falls back to the intro.', max_length=170, null=True)),
                ('meta_description_ar', models.CharField(blank=True, help_text='Around 155 characters. Falls back to the intro.', max_length=170, null=True)),
                ('og_image', models.ImageField(blank=True, help_text='Social sharing image. 1200x630 works everywhere.', upload_to=apps.core.uploads.UploadTo('og'), validators=[apps.core.uploads.validate_upload_size])),
                ('noindex', models.BooleanField(default=False, help_text='Ask search engines not to index this page. Leave off unless you mean it.')),
                ('title', models.CharField(max_length=180)),
                ('title_en', models.CharField(max_length=180, null=True)),
                ('title_es', models.CharField(max_length=180, null=True)),
                ('title_fr', models.CharField(max_length=180, null=True)),
                ('title_de', models.CharField(max_length=180, null=True)),
                ('title_zh', models.CharField(max_length=180, null=True)),
                ('title_ar', models.CharField(max_length=180, null=True)),
                ('slug', models.SlugField(max_length=180, unique=True, validators=[django.core.validators.RegexValidator(message='Lower-case English words separated by single hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('excerpt', models.TextField()),
                ('excerpt_en', models.TextField(null=True)),
                ('excerpt_es', models.TextField(null=True)),
                ('excerpt_fr', models.TextField(null=True)),
                ('excerpt_de', models.TextField(null=True)),
                ('excerpt_zh', models.TextField(null=True)),
                ('excerpt_ar', models.TextField(null=True)),
                ('body', models.TextField()),
                ('body_en', models.TextField(null=True)),
                ('body_es', models.TextField(null=True)),
                ('body_fr', models.TextField(null=True)),
                ('body_de', models.TextField(null=True)),
                ('body_zh', models.TextField(null=True)),
                ('body_ar', models.TextField(null=True)),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('blog'), validators=[apps.core.uploads.validate_upload_size])),
                ('reading_minutes', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='core.teammember')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='services.service')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
