# Generated by Django 5.2.17 on 2026-10-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_the_six_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Set automatically the first time this is published.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', help_text='Only published rows are served to the public site.', max_length=16),
        ),
    ]
