# Generated by Django 5.2.17 on 2026-10-01 22:37

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_published_at_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('services'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='service',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Social sharing image. 1200x630 works everywhere.', upload_to=apps.core.uploads.UploadTo('og'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
    ]
