# Generated by Django 5.2.17 on 2026-10-01 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Leave empty for a company-wide number shown on the home page.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='services.service'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Which service this is about. Leave empty for a general testimonial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='services.service'),
        ),
    ]
