# Generated by Django 5.2.17 on 2026-10-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_site_settings_company_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='translation_status',
            field=models.CharField(choices=[('none', 'Not translated'), ('machine', 'Machine translated'), ('reviewed', 'Reviewed by a human')], db_index=True, default='none', help_text="Set to 'Machine translated' by the auto-translate action. A human sets it to 'Reviewed' after checking the wording.", max_length=16),
        ),
        migrations.AddField(
            model_name='stat',
            name='translation_status',
            field=models.CharField(choices=[('none', 'Not translated'), ('machine', 'Machine translated'), ('reviewed', 'Reviewed by a human')], db_index=True, default='none', help_text="Set to 'Machine translated' by the auto-translate action. A human sets it to 'Reviewed' after checking the wording.", max_length=16),
        ),
        migrations.AddField(
            model_name='teammember',
            name='translation_status',
            field=models.CharField(choices=[('none', 'Not translated'), ('machine', 'Machine translated'), ('reviewed', 'Reviewed by a human')], db_index=True, default='none', help_text="Set to 'Machine translated' by the auto-translate action. A human sets it to 'Reviewed' after checking the wording.", max_length=16),
        ),
    ]
