# Generated by Django 5.2.17 on 2026-10-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_translation_status_on_translatables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'pk']},
        ),
    ]
