# Generated by Django 5.2.17 on 2026-10-01 19:15

import apps.core.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_stat_options_alter_teammember_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation_status', models.CharField(choices=[('none', 'Not translated'), ('machine', 'Machine translated'), ('reviewed', 'Reviewed by a human')], db_index=True, default='none', help_text="Set to 'Machine translated' by the auto-translate action. A human sets it to 'Reviewed' after checking the wording.", max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', help_text='Only published rows are served to the public site.', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically the first time this is published.', null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=180)),
                ('title_en', models.CharField(max_length=180, null=True)),
                ('title_es', models.CharField(max_length=180, null=True)),
                ('title_fr', models.CharField(max_length=180, null=True)),
                ('title_de', models.CharField(max_length=180, null=True)),
                ('title_zh', models.CharField(max_length=180, null=True)),
                ('title_ar', models.CharField(max_length=180, null=True)),
                ('slug', models.SlugField(max_length=180, unique=True, validators=[django.core.validators.RegexValidator(message='Lower-case English words separated by single hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('description_zh', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('orientation', models.CharField(choices=[('landscape', 'Landscape (16:9)'), ('portrait', 'Portrait (9:16)')], max_length=12)),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('file', 'Uploaded file')], default='youtube', max_length=10)),
                ('external_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, upload_to=apps.core.uploads.UploadTo('videos', frozenset(['.mp4', '.webm'])), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_media_file])),
                ('poster_image', models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('videos/posters'), validators=[apps.core.uploads.validate_upload_size])),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('captions_url', models.URLField(blank=True, help_text='URL of a captions track, when available.')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
