# Generated by Django 5.2.17 on 2026-10-01 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_video_case_study'),
        ('products', '0001_initial'),
        ('services', '0003_service_published_at_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='products.product'),
        ),
        migrations.AddField(
            model_name='video',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='services.service'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', True), ('service__isnull', True)), models.Q(('case_study__isnull', True), ('service__isnull', True)), models.Q(('case_study__isnull', True), ('product__isnull', True)), _connector='OR'), name='video_at_most_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_url', ''), ('source', 'file'), models.Q(('video_file', ''), _negated=True)), models.Q(('source__in', ['youtube', 'vimeo']), ('video_file', ''), models.Q(('external_url', ''), _negated=True)), _connector='OR'), name='video_source_matches_media'),
        ),
    ]
