# Generated by Django 5.2.17 on 2026-10-01 22:37

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_video_product_video_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='default_og_image',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('og'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('brand'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('brand'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='For light backgrounds. The site is dark-first, so this is the exception.', upload_to=apps.core.uploads.UploadTo('brand'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('team'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('testimonials'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='tool',
            name='logo',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('tools'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='video',
            name='poster_image',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('videos/posters'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, upload_to=apps.core.uploads.UploadTo('videos', frozenset(['.mp4', '.webm'])), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_video_file]),
        ),
    ]
