# Generated by Django 5.2.17 on 2026-10-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_sitesettings_default_og_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="response_time",
            field=models.CharField(
                blank=True,
                help_text="Public response-time expectation. Leave blank until confirmed.",
                max_length=180,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="response_time_ar",
            field=models.CharField(
                blank=True,
                help_text="Public response-time expectation. Leave blank until confirmed.",
                max_length=180,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="response_time_de",
            field=models.CharField(
                blank=True,
                help_text="Public response-time expectation. Leave blank until confirmed.",
                max_length=180,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="response_time_en",
            field=models.CharField(
                blank=True,
                help_text="Public response-time expectation. Leave blank until confirmed.",
                max_length=180,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="response_time_es",
            field=models.CharField(
                blank=True,
                help_text="Public response-time expectation. Leave blank until confirmed.",
                max_length=180,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="response_time_fr",
            field=models.CharField(
                blank=True,
                help_text="Public response-time expectation. Leave blank until confirmed.",
                max_length=180,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="response_time_zh",
            field=models.CharField(
                blank=True,
                help_text="Public response-time expectation. Leave blank until confirmed.",
                max_length=180,
                null=True,
            ),
        ),
    ]
