# Generated by Django 5.2.17 on 2026-10-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_casestudy_client_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['order', 'pk'], 'verbose_name_plural': 'Case studies'},
        ),
    ]
