# Generated by Django 5.2.17 on 2026-10-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_software', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databasecapability',
            options={'ordering': ['order', 'pk'], 'verbose_name_plural': 'Database capabilities'},
        ),
    ]
