# Generated by Django 5.2.17 on 2026-10-01 19:15

import apps.core.uploads
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation_status', models.CharField(choices=[('none', 'Not translated'), ('machine', 'Machine translated'), ('reviewed', 'Reviewed by a human')], db_index=True, default='none', help_text="Set to 'Machine translated' by the auto-translate action. A human sets it to 'Reviewed' after checking the wording.", max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', help_text='Only published rows are served to the public site.', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically the first time this is published.', null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=180)),
                ('title_en', models.CharField(max_length=180, null=True)),
                ('title_es', models.CharField(max_length=180, null=True)),
                ('title_fr', models.CharField(max_length=180, null=True)),
                ('title_de', models.CharField(max_length=180, null=True)),
                ('title_zh', models.CharField(max_length=180, null=True)),
                ('title_ar', models.CharField(max_length=180, null=True)),
                ('slug', models.SlugField(max_length=180, unique=True, validators=[django.core.validators.RegexValidator(message='Lower-case English words separated by single hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('client_name', models.CharField(max_length=160)),
                ('objective', models.TextField()),
                ('objective_en', models.TextField(null=True)),
                ('objective_es', models.TextField(null=True)),
                ('objective_fr', models.TextField(null=True)),
                ('objective_de', models.TextField(null=True)),
                ('objective_zh', models.TextField(null=True)),
                ('objective_ar', models.TextField(null=True)),
                ('summary', models.TextField()),
                ('summary_en', models.TextField(null=True)),
                ('summary_es', models.TextField(null=True)),
                ('summary_fr', models.TextField(null=True)),
                ('summary_de', models.TextField(null=True)),
                ('summary_zh', models.TextField(null=True)),
                ('summary_ar', models.TextField(null=True)),
                ('results', models.TextField(blank=True)),
                ('results_en', models.TextField(blank=True, null=True)),
                ('results_es', models.TextField(blank=True, null=True)),
                ('results_fr', models.TextField(blank=True, null=True)),
                ('results_de', models.TextField(blank=True, null=True)),
                ('results_zh', models.TextField(blank=True, null=True)),
                ('results_ar', models.TextField(blank=True, null=True)),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('google', 'Google'), ('other', 'Other')], max_length=20), blank=True, default=list, size=None)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('campaigns'), validators=[apps.core.uploads.validate_upload_size])),
                ('reach', models.PositiveBigIntegerField(blank=True, null=True)),
                ('engagement_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage, 0 to 100. Leave empty when unknown.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('conversions', models.PositiveIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreativeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation_status', models.CharField(choices=[('none', 'Not translated'), ('machine', 'Machine translated'), ('reviewed', 'Reviewed by a human')], db_index=True, default='none', help_text="Set to 'Machine translated' by the auto-translate action. A human sets it to 'Reviewed' after checking the wording.", max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', help_text='Only published rows are served to the public site.', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically the first time this is published.', null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('poster', 'Poster'), ('graphic', 'Graphic'), ('reel', 'Reel'), ('banner', 'Banner'), ('motion', 'Motion')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('title_en', models.CharField(max_length=180, null=True)),
                ('title_es', models.CharField(max_length=180, null=True)),
                ('title_fr', models.CharField(max_length=180, null=True)),
                ('title_de', models.CharField(max_length=180, null=True)),
                ('title_zh', models.CharField(max_length=180, null=True)),
                ('title_ar', models.CharField(max_length=180, null=True)),
                ('slug', models.SlugField(max_length=180, unique=True, validators=[django.core.validators.RegexValidator(message='Lower-case English words separated by single hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('description_zh', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('creative/thumbnails'), validators=[apps.core.uploads.validate_upload_size])),
                ('file', models.FileField(blank=True, upload_to=apps.core.uploads.UploadTo('creative', frozenset(['.avif', '.gif', '.jpeg', '.jpg', '.mp4', '.png', '.webm', '.webp'])), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_media_file])),
                ('external_url', models.URLField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('google', 'Google'), ('other', 'Other')], max_length=20)),
                ('slug', models.SlugField(max_length=180, unique=True, validators=[django.core.validators.RegexValidator(message='Lower-case English words separated by single hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('handle', models.CharField(max_length=160)),
                ('url', models.URLField()),
                ('follower_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_managed_for_clients', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
