# Generated by Django 5.2.17 on 2026-10-01 22:37

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_marketing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('campaigns'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('creative/thumbnails'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
    ]
