# Generated by Django 5.2.17 on 2026-10-01 19:15

import apps.core.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation_status', models.CharField(choices=[('none', 'Not translated'), ('machine', 'Machine translated'), ('reviewed', 'Reviewed by a human')], db_index=True, default='none', help_text="Set to 'Machine translated' by the auto-translate action. A human sets it to 'Reviewed' after checking the wording.", max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', help_text='Only published rows are served to the public site.', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically the first time this is published.', null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True, validators=[django.core.validators.RegexValidator(message='Lower-case English words separated by single hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('icon', models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(message='Use a Material Symbols name in lower_snake_case, e.g. shield_lock.', regex='^[a-z0-9_]+$')])),
                ('issuer', models.CharField(max_length=160)),
                ('logo', models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('certifications'), validators=[apps.core.uploads.validate_upload_size])),
                ('credential_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComplianceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation_status', models.CharField(choices=[('none', 'Not translated'), ('machine', 'Machine translated'), ('reviewed', 'Reviewed by a human')], db_index=True, default='none', help_text="Set to 'Machine translated' by the auto-translate action. A human sets it to 'Reviewed' after checking the wording.", max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', help_text='Only published rows are served to the public site.', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically the first time this is published.', null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True, validators=[django.core.validators.RegexValidator(message='Lower-case English words separated by single hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('description_zh', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(message='Use a Material Symbols name in lower_snake_case, e.g. shield_lock.', regex='^[a-z0-9_]+$')])),
                ('logo', models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('compliance'), validators=[apps.core.uploads.validate_upload_size])),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation_status', models.CharField(choices=[('none', 'Not translated'), ('machine', 'Machine translated'), ('reviewed', 'Reviewed by a human')], db_index=True, default='none', help_text="Set to 'Machine translated' by the auto-translate action. A human sets it to 'Reviewed' after checking the wording.", max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', help_text='Only published rows are served to the public site.', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically the first time this is published.', null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=160)),
                ('name_en', models.CharField(max_length=160, null=True)),
                ('name_es', models.CharField(max_length=160, null=True)),
                ('name_fr', models.CharField(max_length=160, null=True)),
                ('name_de', models.CharField(max_length=160, null=True)),
                ('name_zh', models.CharField(max_length=160, null=True)),
                ('name_ar', models.CharField(max_length=160, null=True)),
                ('slug', models.SlugField(max_length=180, unique=True, validators=[django.core.validators.RegexValidator(message='Lower-case English words separated by single hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('description_zh', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(message='Use a Material Symbols name in lower_snake_case, e.g. shield_lock.', regex='^[a-z0-9_]+$')])),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
