# Generated by Django 5.2.17 on 2026-10-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyber_security', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberSecurityCaseStudy',
            fields=[
            ],
            options={
                'verbose_name': 'Case study',
                'verbose_name_plural': 'Case studies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portfolio.casestudy',),
        ),
    ]
