# Generated by Django 5.2.17 on 2026-10-01 22:37

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.UploadTo('products'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Social sharing image. 1200x630 works everywhere.', upload_to=apps.core.uploads.UploadTo('og'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=apps.core.uploads.UploadTo('products/gallery'), validators=[apps.core.uploads.validate_upload_size, apps.core.uploads.validate_image_file]),
        ),
    ]
