# Generated by Django 5.2.17 on 2026-10-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_development', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webcapability',
            options={'ordering': ['order', 'pk'], 'verbose_name_plural': 'Web capabilities'},
        ),
    ]
